services:
    selling-clothes-frontend:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env  # Dòng này giúp docker-compose nạp file .env
        container_name: selling-clothes-app
        ports:
            - "80:80"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: always
